USE greenspot;
INSERT INTO categories (category_name) VALUES ('Canned');
INSERT INTO categories (category_name) VALUES ('Dairy');
INSERT INTO categories (category_name) VALUES ('Produce');
INSERT INTO storage_locations (location_code) VALUES ('D12');
INSERT INTO storage_locations (location_code) VALUES ('a2');
INSERT INTO storage_locations (location_code) VALUES ('a3');
INSERT INTO storage_locations (location_code) VALUES ('a7');
INSERT INTO storage_locations (location_code) VALUES ('d12');
INSERT INTO storage_locations (location_code) VALUES ('p12');
INSERT INTO storage_locations (location_code) VALUES ('po2');
INSERT INTO suppliers (supplier_name) VALUES ('Bennet Farms, Rt. 17 Evansville, IL 55446');
INSERT INTO suppliers (supplier_name) VALUES ('Freshness, Inc., 202 E. Maple St., St. Joseph, MO 45678');
INSERT INTO suppliers (supplier_name) VALUES ('Ruby Redd Produce, LLC, 1212 Milam St., Kenosha, AL, 34567');
INSERT INTO customers (external_ref) VALUES ('100988');
INSERT INTO customers (external_ref) VALUES ('111000');
INSERT INTO customers (external_ref) VALUES ('196777');
INSERT INTO customers (external_ref) VALUES ('198765');
INSERT INTO customers (external_ref) VALUES ('202900');
INSERT INTO customers (external_ref) VALUES ('277177');
INSERT INTO customers (external_ref) VALUES ('nan');
INSERT INTO products (sku, product_name, category_id, unit_of_measure, price, default_location_id) VALUES ('1000.0','Bennet Farm free-range eggs',2,'dozen',5.49,1);
INSERT INTO products (sku, product_name, category_id, unit_of_measure, price, default_location_id) VALUES ('2000.0','Ruby''s Kale',3,'bunch',3.99,6);
INSERT INTO products (sku, product_name, category_id, unit_of_measure, price, default_location_id) VALUES ('1100.0','Freshness White beans',1,'12 ounce can',1.49,2);
INSERT INTO products (sku, product_name, category_id, unit_of_measure, price, default_location_id) VALUES ('1100.0','Freshness White beans',1,'12 oz can',1.49,2);
INSERT INTO products (sku, product_name, category_id, unit_of_measure, price, default_location_id) VALUES ('1100.0','Freshness White beans',1,'12-oz can',1.49,2);
INSERT INTO products (sku, product_name, category_id, unit_of_measure, price, default_location_id) VALUES ('1222.0','Freshness Green beans',1,'12 ounce can',1.29,3);
INSERT INTO products (sku, product_name, category_id, unit_of_measure, price, default_location_id) VALUES ('1223.0','Freshness Green beans',1,'36 oz can',3.49,4);
INSERT INTO products (sku, product_name, category_id, unit_of_measure, price, default_location_id) VALUES ('1224.0','Freshness Wax beans',1,'12 ounce can',1.55,3);
INSERT INTO products (sku, product_name, category_id, unit_of_measure, price, default_location_id) VALUES ('1222.0','Freshness Green beans',1,'12-oz can',1.29,3);
INSERT INTO products (sku, product_name, category_id, unit_of_measure, price, default_location_id) VALUES ('1224.0','Freshness Wax beans',1,'12-oz can',1.55,3);
INSERT INTO products (sku, product_name, category_id, unit_of_measure, price, default_location_id) VALUES ('2001.0','Ruby''s Organic Kale',3,'bunch',6.99,7);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (1, 'purchase', '2/1/2022', 1, 1, NULL, NULL, 2.35, NULL, 29.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (1, 'sale', 'nan', 1, NULL, 7, -25.0, NULL, NULL, 29.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (1, 'purchase', 'nan', 1, NULL, NULL, NULL, NULL, NULL, 27.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (1, 'sale', '2/2/2022', 1, NULL, 4, -2.0, NULL, 5.49, 27.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (2, 'purchase', 'nan', 6, NULL, NULL, NULL, NULL, NULL, 3.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (2, 'sale', '2/2/2022', 6, NULL, NULL, -2.0, NULL, 3.99, 3.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (5, 'purchase', 'nan', 2, NULL, NULL, NULL, NULL, NULL, 13.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (5, 'sale', '2/2/2022', 2, NULL, 5, -2.0, NULL, 1.49, 13.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (5, 'purchase', '2/2/2022', 2, 2, NULL, NULL, 0.69, NULL, 53.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (5, 'sale', 'nan', 2, NULL, 7, -40.0, NULL, NULL, 53.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (1, 'purchase', 'nan', 1, NULL, NULL, NULL, NULL, NULL, 25.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (1, 'sale', '2/4/2022', 1, NULL, 3, -2.0, NULL, 5.99, 25.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (5, 'purchase', 'nan', 2, NULL, NULL, NULL, NULL, NULL, 45.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (5, 'sale', '2/7/2022', 2, NULL, 4, -8.0, NULL, 1.49, 45.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (9, 'purchase', '2/10/2022', 3, 2, NULL, NULL, 0.59, NULL, 59.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (9, 'sale', 'nan', 3, NULL, 7, -40.0, NULL, NULL, 59.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (7, 'purchase', '2/10/2022', 4, 2, NULL, NULL, 1.75, NULL, 12.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (7, 'sale', 'nan', 4, NULL, 7, -10.0, NULL, NULL, 12.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (10, 'purchase', '2/10/2022', 3, 2, NULL, NULL, 0.65, NULL, 31.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (10, 'sale', 'nan', 3, NULL, 7, -30.0, NULL, NULL, 31.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (1, 'purchase', 'nan', 5, NULL, NULL, NULL, NULL, NULL, 21.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (1, 'sale', '2/11/2022', 5, NULL, 6, -4.0, NULL, 5.49, 21.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (5, 'purchase', 'nan', 2, NULL, NULL, NULL, NULL, NULL, 41.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (5, 'sale', '2/11/2022', 2, NULL, 7, -4.0, NULL, 1.49, 41.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (9, 'purchase', 'nan', 3, NULL, NULL, NULL, NULL, NULL, 47.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (9, 'sale', '2/12/2022', 3, NULL, 2, -12.0, NULL, 1.29, 47.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (10, 'purchase', 'nan', 3, NULL, NULL, NULL, NULL, NULL, 23.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (10, 'sale', '2/12/2022', 3, NULL, 7, -8.0, NULL, 1.55, 23.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (2, 'purchase', '2/12/2022', 6, 3, NULL, NULL, 1.29, NULL, 28.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (2, 'sale', 'nan', 6, NULL, 7, -25.0, NULL, NULL, 28.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (11, 'purchase', '2/12/2022', 7, 3, NULL, NULL, 2.19, NULL, 20.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (11, 'sale', 'nan', 7, NULL, 7, -20.0, NULL, NULL, 20.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (7, 'purchase', 'nan', 4, NULL, NULL, NULL, NULL, NULL, 7.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (7, 'sale', '2/13/2022', 4, NULL, 4, -5.0, NULL, 3.49, 7.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (11, 'purchase', 'nan', 7, NULL, NULL, NULL, NULL, NULL, 19.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (11, 'sale', '2/13/2022', 7, NULL, 1, -1.0, NULL, 6.99, 19.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (11, 'purchase', 'nan', 7, NULL, NULL, NULL, NULL, NULL, 7.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (11, 'sale', '2/14/2022', 7, NULL, 5, -12.0, NULL, 6.99, 7.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (7, 'purchase', '2/15/2022', 4, 2, NULL, NULL, 1.8, NULL, 17.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (7, 'sale', 'nan', 4, NULL, 7, -10.0, NULL, NULL, 17.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (2, 'purchase', 'nan', 6, NULL, NULL, NULL, NULL, NULL, 26.0);
INSERT INTO stock_transactions (product_id, event_type, event_date, location_id, vendor_id, customer_id, qty_change, unit_cost, unit_price, on_hand_after) VALUES (2, 'sale', '2/15/2022', 6, NULL, 2, -2.0, NULL, 3.99, 26.0);
